// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1e0uzbKzqh5SVjSLCuPx3B1QNProUtw',
    appId: '1:158705608646:web:631be3d3cdda1683f574c7',
    messagingSenderId: '158705608646',
    projectId: 'yadu1-821e8',
    authDomain: 'yadu1-821e8.firebaseapp.com',
    storageBucket: 'yadu1-821e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsKB02gsyQLFVF6IQSFa0iK9e0EojeQ3U',
    appId: '1:158705608646:android:b74d321cd8904c76f574c7',
    messagingSenderId: '158705608646',
    projectId: 'yadu1-821e8',
    storageBucket: 'yadu1-821e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBd2VNz0yX0TYRyEY-vI1fKLzhwmOOlN0',
    appId: '1:158705608646:ios:ae3b0a3cbeea8c0df574c7',
    messagingSenderId: '158705608646',
    projectId: 'yadu1-821e8',
    storageBucket: 'yadu1-821e8.firebasestorage.app',
    iosBundleId: 'com.dairydelivery.dairyDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBd2VNz0yX0TYRyEY-vI1fKLzhwmOOlN0',
    appId: '1:158705608646:ios:ae3b0a3cbeea8c0df574c7',
    messagingSenderId: '158705608646',
    projectId: 'yadu1-821e8',
    storageBucket: 'yadu1-821e8.firebasestorage.app',
    iosBundleId: 'com.dairydelivery.dairyDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR1e0uzbKzqh5SVjSLCuPx3B1QNProUtw',
    appId: '1:158705608646:web:b8ba8f491fe8c1eaf574c7',
    messagingSenderId: '158705608646',
    projectId: 'yadu1-821e8',
    authDomain: 'yadu1-821e8.firebaseapp.com',
    storageBucket: 'yadu1-821e8.firebasestorage.app',
  );
}
